# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'concertApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for concertApp
  pod 'AFNetworking'
  pod 'Unirest'

  target 'concertAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'concertAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
